plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls']
}

application {
    mainClass = 'ru.ineprokin.Main'
}

sourceSets {
    main {
        java.srcDirs = ['src']
        resources.srcDirs = []
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
